### ISSUE TITLE
Error during creation Uber API service object

### ISSUE THREAD

**Issue by arthur-kalmykov** [uber/rides-java-sdk#9]
UberRidesSyncService service = UberRidesServices.createSync(session); I'm catching the java.lang.NoSuchMethodError. Can someone help? jdk1.8.0_73

> 
Exception in thread "main" java.lang.NoSuchMethodError: com.squareup.okhttp.OkHttpClient.setFollowRedirects(Z)V
	at com.uber.sdk.rides.client.internal.RetrofitUberRidesClient.buildRestAdapter(RetrofitUberRidesClient.java:147)
	at com.uber.sdk.rides.client.internal.RetrofitUberRidesClient.getUberApiService(RetrofitUberRidesClient.java:102)
	at com.uber.sdk.rides.client.internal.RetrofitUberRidesClient.getUberApiService(RetrofitUberRidesClient.java:77)
	at com.uber.sdk.rides.client.UberRidesServices.create(UberRidesServices.java:182)
	at com.uber.sdk.rides.client.UberRidesServices.access$100(UberRidesServices.java:66)
	at com.uber.sdk.rides.client.UberRidesServices$Builder.build(UberRidesServices.java:131)
	at com.uber.sdk.rides.client.UberRidesServices.createSync(UberRidesServices.java:153)
	at uber.UberController.<init>(UberController.java:44)
	at uber.UberController.getInstance(UberController.java:82)
	at uber.UberController.main(UberController.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by itstexter** [comment]
Can you show me how you are creating your session? Currently just the line UberRidesSyncService service = UberRidesServices.createSync(session); work for me right now.

**Comment by arthur-kalmykov** [comment]
Session session = new Session.Builder()
    .setServerToken("*SERVER_TOKEN*")
    .setEnvironment(Environment.PRODUCTION)
    .build();
UberRidesSyncService service = UberRidesServices.createSync(session);
And thats all. 
With OAuth2Credentials I have the same error :( It happens on line "UberRidesSyncService service = UberRidesServices.createSync(session);"

**Comment by itstexter** [comment]
Hmm I just tried this on the sample and it worked for me (with a valid Server Token).

Could you try to download release [v0.2.0](https://github.com/uber/rides-java-sdk/releases/tag/v0.2.0) and run the sample?  Trying to figure out if it's a bug with the setup environment or the SDK.

**Comment by arthur-kalmykov** [comment]
It strange. Sample is working. Intellij idea gives thats exception. Even if I'm trying to copy sample into idea... :(

**Comment by arthur-kalmykov** [comment]
Problem was solved by adding dependency in maven. You can write it in README, because it was intuitive desision. 

> <dependency>
>             <groupId>com.squareup.okhttp</groupId>
>             <artifactId>okhttp</artifactId>
>             <version>2.2.0</version>
>  </dependency>
